# Generated by Django 4.1.2 on 2022-11-22 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0002_alter_project_id_alter_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='projectID',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
