# Generated by Django 4.1.2 on 2022-11-22 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0003_project_projectid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-projectID']},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-task_number']},
        ),
        migrations.AddField(
            model_name='task',
            name='task_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
