# Generated by Django 4.1.2 on 2022-11-23 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0004_alter_project_options_alter_task_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='status',
        ),
        migrations.AlterField(
            model_name='task',
            name='end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='start',
            field=models.DateField(),
        ),
    ]
