# Generated by Django 4.1.2 on 2022-11-24 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0005_remove_project_status_alter_task_end_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskprogess',
            old_name='work_complation',
            new_name='work_completion',
        ),
    ]
