# Generated by Django 4.1.2 on 2022-11-24 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0006_projectfile_title'),
        ('Projects', '0006_rename_work_complation_taskprogess_work_completion'),
    ]

    operations = [
    ]
