# Generated by Django 4.1.2 on 2022-11-24 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0007_merge_20221124_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectnote',
            name='noteID',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
