# Generated by Django 4.1.2 on 2022-11-24 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0009_alter_projectnote_options_alter_projectnote_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='is_deleted',
            new_name='is_delete',
        ),
        migrations.RenameField(
            model_name='projectfile',
            old_name='is_deleted',
            new_name='is_delete',
        ),
        migrations.RenameField(
            model_name='projectnote',
            old_name='is_deleted',
            new_name='is_delete',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='is_deleted',
            new_name='is_delete',
        ),
        migrations.RenameField(
            model_name='taskfile',
            old_name='is_deleted',
            new_name='is_delete',
        ),
        migrations.RenameField(
            model_name='tasknote',
            old_name='is_deleted',
            new_name='is_delete',
        ),
        migrations.RenameField(
            model_name='taskprogess',
            old_name='is_deleted',
            new_name='is_delete',
        ),
    ]
