# Generated by Django 4.1.2 on 2022-11-24 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0010_rename_is_deleted_project_is_delete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskfile',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
