# Generated by Django 4.1.2 on 2022-11-24 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0011_taskfile_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasknote',
            name='noteID',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
