# Generated by Django 4.1.2 on 2022-11-26 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0012_tasknote_noteid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-task_number'], 'permissions': [('change_priority_task', 'Can change priority tasks')]},
        ),
        migrations.AlterModelOptions(
            name='tasknote',
            options={'ordering': ['-noteID']},
        ),
        migrations.AlterModelTable(
            name='assigntask',
            table='assign_task',
        ),
        migrations.AlterModelTable(
            name='project',
            table='project',
        ),
        migrations.AlterModelTable(
            name='projectfile',
            table='project_file',
        ),
        migrations.AlterModelTable(
            name='projectnote',
            table='project_note',
        ),
        migrations.AlterModelTable(
            name='task',
            table='task',
        ),
        migrations.AlterModelTable(
            name='taskfile',
            table='task_file',
        ),
        migrations.AlterModelTable(
            name='tasknote',
            table='task_note',
        ),
        migrations.AlterModelTable(
            name='taskprogess',
            table='task_progress',
        ),
    ]
