# Generated by Django 4.1.2 on 2022-12-03 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0016_notifications'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-projectID'], 'permissions': [('project_visibility', 'Manager can view their assigned projects')]},
        ),
    ]
