# Generated by Django 4.1.2 on 2022-12-07 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0017_alter_project_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='projectnote',
            name='note',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='taskcomments',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tasknote',
            name='note',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='taskprogess',
            name='description',
            field=models.TextField(),
        ),
    ]
