# Generated by Django 4.1.2 on 2022-12-07 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0004_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replyticket',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='description',
            field=models.TextField(),
        ),
    ]
