# Generated by Django 4.1.2 on 2022-12-22 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
        ('Tickets', '0005_alter_replyticket_message_alter_tickets_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerLease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computer_tag', models.CharField(max_length=500)),
                ('full_name', models.CharField(blank=True, max_length=500, null=True)),
                ('username', models.CharField(max_length=500)),
                ('office_key', models.CharField(max_length=500)),
                ('office_type', models.CharField(max_length=500)),
                ('windows_key', models.CharField(max_length=500)),
                ('windows_type', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=500)),
                ('bitlocker_recovery_keys', models.CharField(max_length=500)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.department')),
            ],
        ),
    ]
