# Generated by Django 4.1.2 on 2022-12-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0006_computerlease'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computerlease',
            name='username',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
