# Generated by Django 4.1.2 on 2022-12-22 09:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0007_alter_computerlease_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='computerlease',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.today, null=True),
        ),
        migrations.AddField(
            model_name='computerlease',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='computerlease',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
