# Generated by Django 4.1.2 on 2022-12-22 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0008_computerlease_created_at_computerlease_is_delete_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='computerlease',
            table='computers',
        ),
    ]
