# Generated by Django 4.1.2 on 2022-12-22 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0009_alter_computerlease_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computerlease',
            name='bitlocker_recovery_keys',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='computerlease',
            name='computer_tag',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='computerlease',
            name='full_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='computerlease',
            name='office_key',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='computerlease',
            name='windows_key',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
